### ISSUE TITLE
No docker error from WindNinja

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/katana#2]
When WindNinja crashes the docker still exits successfully and does not throw an error.

**Comment by scotthavens** [comment]
While not tested, this should be fixed with PR #13. The `Popen` call that calls `WindNinja_cli` does a better job at catching errors from the command line. There is now a `wait()` that gets the return code of the `Popen` and will raise an exception if there is a return code that is not successful. There are a few tests in PR #13 to test some of the error catching but has not been tested in docker.
